# Generated by Django 5.0.1 on 2026-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(choices=[('metadata_similarity', "Metadata o'xshashligi"), ('price_anomaly', 'Narx anomaliyasi'), ('content_similarity', "Matn o'xshashligi"), ('ip_similarity', "IP manzil o'xshashligi"), ('time_pattern', 'Vaqt patterni'), ('document_pattern', 'Hujjat patterni')], max_length=30, verbose_name='Aniqlash turi')),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Tanqidiy')], max_length=20, verbose_name='Jiddiylik darajasi')),
                ('status', models.CharField(choices=[('detected', 'Aniqlangan'), ('reviewing', "Ko'rib chiqilmoqda"), ('confirmed', 'Tasdiqlangan'), ('false_positive', 'Xato signal'), ('resolved', 'Hal qilingan')], default='detected', max_length=20, verbose_name='Holati')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Xavf balli')),
                ('detection_data', models.JSONField(default=dict, verbose_name="Aniqlash ma'lumotlari")),
                ('evidence', models.JSONField(default=list, verbose_name='Dalillar')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Tekshiruv izohlari')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Korrupsiya aniqlash',
                'verbose_name_plural': 'Korrupsiya aniqlashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudDetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Qoida nomi')),
                ('rule_type', models.CharField(choices=[('metadata', 'Metadata qoidasi'), ('price', 'Narx qoidasi'), ('similarity', "O'xshashlik qoidasi"), ('time', 'Vaqt qoidasi'), ('behavior', 'Xulq-atvor qoidasi')], max_length=20, verbose_name='Qoida turi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('conditions', models.JSONField(default=dict, verbose_name='Shartlar')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=' chegarasi')),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Tanqidiy')], max_length=20, verbose_name='Jiddiylik darajasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioritet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Korrupsiya aniqlash qoidasi',
                'verbose_name_plural': 'Korrupsiya aniqlash qoidalari',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_software', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yaratilgan dastur')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi o'zgartirish")),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Muallif')),
                ('file_size', models.BigIntegerField(verbose_name='Fayl hajmi')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Sahifalar soni')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name="So'zlar soni")),
                ('similarity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="O'xshashlik balli")),
                ('risk_level', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Tanqidiy')], default='low', max_length=20, verbose_name='Xavf darajasi')),
                ('analysis_result', models.JSONField(default=dict, verbose_name='Tahlil natijalari')),
                ('flags', models.JSONField(default=list, verbose_name='Bayroqlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metadata tahlili',
                'verbose_name_plural': 'Metadata tahlillari',
            },
        ),
        migrations.CreateModel(
            name='PriceAnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('too_low', 'Juda past narx'), ('too_high', 'Juda yuqori narx'), ('unnatural_round', "Sun'iy yaxlitlangan narx"), ('suspicious_pattern', 'Shubhali pattern'), ('market_deviation', 'Bozordan chetlanish')], max_length=30, verbose_name='Anomaliya turi')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Taklif etilgan narx')),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kutilgan narx')),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bozor narxi')),
                ('deviation_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chetlanish foizi')),
                ('z_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Z-score')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Xavf balli')),
                ('analysis_data', models.JSONField(default=dict, verbose_name="Tahlil ma'lumotlari")),
                ('recommendation', models.TextField(verbose_name='Tavsiya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Narx anomaliyasi',
                'verbose_name_plural': 'Narx anomaliyalari',
            },
        ),
        migrations.CreateModel(
            name='SimilarityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_type', models.CharField(choices=[('content', 'Matn mazmuni'), ('structure', 'Hujjat tuzilishi'), ('formatting', 'Formatlash'), ('language', 'Til uslubi'), ('tables', 'Jadvallar')], max_length=20, verbose_name="O'xshashlik turi")),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="O'xshashlik balli")),
                ('compared_sections', models.JSONField(default=list, verbose_name="Solishtirilgan bo'limlar")),
                ('matching_phrases', models.JSONField(default=list, verbose_name='Mos keladigan iboralar')),
                ('structural_similarity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Strukturaviy o'xshashlik")),
                ('risk_level', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Tanqidiy')], default='low', max_length=20, verbose_name='Xavf darajasi')),
                ('is_suspicious', models.BooleanField(default=False, verbose_name='Shubhali')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "O'xshashlik tahlili",
                'verbose_name_plural': "O'xshashlik tahlillari",
            },
        ),
    ]
