# Generated by Django 5.0.1 on 2026-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anti_fraud', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frauddetection',
            name='involved_participants',
            field=models.ManyToManyField(related_name='fraud_cases', to='participants.tenderparticipant'),
        ),
    ]
