# Generated by Django 5.0.1 on 2026-01-12 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anti_fraud', '0002_initial'),
        ('participants', '0002_initial'),
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frauddetection',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi'),
        ),
        migrations.AddField(
            model_name='frauddetection',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_detections', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='metadataanalysis',
            name='tender_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_analyses', to='participants.tenderparticipant'),
        ),
        migrations.AddField(
            model_name='priceanomalydetection',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_anomalies', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='priceanomalydetection',
            name='tender_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_anomalies', to='participants.tenderparticipant'),
        ),
        migrations.AddField(
            model_name='similarityanalysis',
            name='participant_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_p1', to='participants.tenderparticipant'),
        ),
        migrations.AddField(
            model_name='similarityanalysis',
            name='participant_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_p2', to='participants.tenderparticipant'),
        ),
        migrations.AddField(
            model_name='similarityanalysis',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_analyses', to='tenders.tender'),
        ),
        migrations.AlterUniqueTogether(
            name='similarityanalysis',
            unique_together={('participant_1', 'participant_2', 'similarity_type')},
        ),
    ]
