# Generated by Django 5.0.1 on 2026-01-07 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Qoida nomi')),
                ('rule_type', models.CharField(choices=[('legal', 'Huquqiy qoida'), ('technical', 'Texnik qoida'), ('financial', 'Moliyaviy qoida'), ('document', 'Hujjat qoidasi'), ('qualification', 'Malaka qoidasi')], max_length=20, verbose_name='Qoida turi')),
                ('regulation_type', models.CharField(choices=[('orq_684', "O'RQ-684"), ('orq_585', "O'RQ-585"), ('orq_437', "O'RQ-437"), ('government_decree', 'Hukumat qarori'), ('ministry_regulation', 'Vazirlik qoidasi'), ('internal', 'Ichki qoida')], max_length=30, verbose_name='Normativ hujjat turi')),
                ('regulation_number', models.CharField(max_length=100, verbose_name='Normativ hujjat raqami')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('requirement', models.TextField(verbose_name='Talab')),
                ('penalty_description', models.TextField(blank=True, null=True, verbose_name='Jarima tavsifi')),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Tanqidiy')], max_length=20, verbose_name='Jiddiylik darajasi')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('validation_rules', models.JSONField(default=dict, verbose_name='Validatsiya qoidalari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('effective_date', models.DateField(verbose_name='Kuchga kirish sanasi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance qoidasi',
                'verbose_name_plural': 'Compliance qoidalari',
                'ordering': ['regulation_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Shablon nomi')),
                ('template_type', models.CharField(choices=[('tender', 'Tender shabloni'), ('proposal', 'Taklif shabloni'), ('contract', 'Shartnoma shabloni'), ('report', 'Hisobot shabloni')], max_length=20, verbose_name='Shablon turi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('required_sections', models.JSONField(default=list, verbose_name="Talab qilinadigan bo'limlar")),
                ('field_validations', models.JSONField(default=dict, verbose_name='Maydon validatsiyalari')),
                ('compliance_rules', models.JSONField(default=list, verbose_name='Compliance qoidalari')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='Shablon fayli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versiya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance shabloni',
                'verbose_name_plural': 'Compliance shablonlari',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=100, unique=True, verbose_name='Hisobot raqami')),
                ('title', models.CharField(max_length=500, verbose_name='Hisobot nomi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('review', "Ko'rib chiqish"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20, verbose_name='Holati')),
                ('total_checks', models.IntegerField(default=0, verbose_name='Jami tekshiruvlar')),
                ('passed_checks', models.IntegerField(default=0, verbose_name="O'tgan tekshiruvlar")),
                ('failed_checks', models.IntegerField(default=0, verbose_name="O'tmagan tekshiruvlar")),
                ('warning_checks', models.IntegerField(default=0, verbose_name='Ogohlantirishlar')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Umumiy ball')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maksimal ball')),
                ('compliance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Compliance foizi')),
                ('critical_violations', models.JSONField(default=list, verbose_name='Tanqidiy buzilishlar')),
                ('major_violations', models.JSONField(default=list, verbose_name='Asosiy buzilishlar')),
                ('minor_violations', models.JSONField(default=list, verbose_name='Kichik buzilishlar')),
                ('recommendations', models.TextField(verbose_name='Tavsiyalar')),
                ('corrective_actions', models.TextField(blank=True, null=True, verbose_name='Tuzatish choralari')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_reports', to=settings.AUTH_USER_MODEL, verbose_name='Tayyorlovchi')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Compliance hisoboti',
                'verbose_name_plural': 'Compliance hisobotlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('passed', "O'tdi"), ('failed', "O'tmadi"), ('warning', 'Ogohlantirish'), ('error', 'Xatolik')], default='pending', max_length=20, verbose_name='Holati')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ball')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maksimal ball')),
                ('check_result', models.JSONField(default=dict, verbose_name='Tekshirish natijasi')),
                ('evidence', models.JSONField(default=list, verbose_name='Dalillar')),
                ('violations', models.JSONField(default=list, verbose_name='Buzilishlar')),
                ('findings', models.TextField(verbose_name='Topilmalar')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Tavsiyalar')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tekshirgan')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='tenders.tender')),
                ('tender_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='participants.tenderparticipant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='compliance.compliancerule')),
            ],
            options={
                'verbose_name': 'Compliance tekshiruvi',
                'verbose_name_plural': 'Compliance tekshiruvlari',
                'ordering': ['-created_at'],
                'unique_together': {('tender_participant', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='DocumentCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('proposal', 'Taklif hujjati'), ('financial', 'Moliyaviy hujjat'), ('technical', 'Texnik hujjat'), ('certificate', 'Sertifikat'), ('license', 'Litsenziya'), ('experience', 'Tajriba hujjati')], max_length=20, verbose_name='Hujjat turi')),
                ('required_sections', models.JSONField(default=list, verbose_name="Talab qilinadigan bo'limlar")),
                ('mandatory_fields', models.JSONField(default=list, verbose_name='Majburiy maydonlar')),
                ('format_requirements', models.JSONField(default=dict, verbose_name='Format talablari')),
                ('is_present', models.BooleanField(default=False, verbose_name='Mavjud')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Yaroqli')),
                ('is_complete', models.BooleanField(default=False, verbose_name="To'liq")),
                ('missing_sections', models.JSONField(default=list, verbose_name="Yo'q bo'limlar")),
                ('invalid_fields', models.JSONField(default=list, verbose_name='Yaroqsiz maydonlar')),
                ('format_issues', models.JSONField(default=list, verbose_name='Format muammolari')),
                ('compliance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Compliance balli')),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Maksimal ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_compliances', to='participants.tenderparticipant')),
            ],
            options={
                'verbose_name': 'Hujjat compliance',
                'verbose_name_plural': 'Hujjat compliancelari',
                'unique_together': {('tender_participant', 'document_type')},
            },
        ),
    ]
