# Generated by Django 5.0.1 on 2026-01-12 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('participants', '0002_initial'),
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tekshirgan'),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='tender_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='participants.tenderparticipant'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_reports', to=settings.AUTH_USER_MODEL, verbose_name='Tayyorlovchi'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='compliancecheck',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='compliance.compliancerule'),
        ),
        migrations.AddField(
            model_name='documentcompliance',
            name='tender_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_compliances', to='participants.tenderparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecheck',
            unique_together={('tender_participant', 'rule')},
        ),
        migrations.AlterUniqueTogether(
            name='documentcompliance',
            unique_together={('tender_participant', 'document_type')},
        ),
    ]
