# Generated by Django 5.0.1 on 2026-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holati')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('total_participants', models.IntegerField(default=0, verbose_name='Jami ishtirokchilar')),
                ('qualified_participants', models.IntegerField(default=0, verbose_name='Saralangan ishtirokchilar')),
                ('disqualified_participants', models.IntegerField(default=0, verbose_name="Saralashdan o'tmaganlar")),
                ('high_risk_count', models.IntegerField(default=0, verbose_name='Yuqori xavfli ishtirokchilar')),
                ('medium_risk_count', models.IntegerField(default=0, verbose_name="O'rta xavfli ishtirokchilar")),
                ('low_risk_count', models.IntegerField(default=0, verbose_name='Past xavfli ishtirokchilar')),
                ('reasoning', models.TextField(blank=True, null=True, verbose_name='Baholash sabablari')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='AI tahlili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('error', 'Xatolik'), ('fraud_detected', 'Korrupsiya aniqlandi'), ('compliance_issue', 'Compliance muammosi')], max_length=20, verbose_name='Log turi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('details', models.JSONField(default=dict, verbose_name='Tafsilotlar')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Agent nomi')),
                ('agent_type', models.CharField(max_length=50, verbose_name='Agent turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Baholash logi',
                'verbose_name_plural': 'Baholash loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Jami ball')),
                ('compliance_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Compliance balli')),
                ('financial_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moliyaviy ball')),
                ('technical_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Texnik ball')),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tajriba balli')),
                ('risk_level', models.CharField(choices=[('low', 'Past xavf'), ('medium', "O'rta xavf"), ('high', 'Yuqori xavf'), ('critical', 'Tanqidiy xavf')], default='low', max_length=20, verbose_name='Xavf darajasi')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Xavf balli')),
                ('red_flags', models.JSONField(default=list, verbose_name='Xavf belgilari')),
                ('warnings', models.JSONField(default=list, verbose_name='Ogohlantirishlar')),
                ('score_reasoning', models.TextField(verbose_name='Ball berish sabablari')),
                ('risk_reasoning', models.TextField(blank=True, null=True, verbose_name='Xavf sabablari')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name="O'rni")),
                ('is_winner', models.BooleanField(default=False, verbose_name="G'olib")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ishtirokchi balli',
                'verbose_name_plural': 'Ishtirokchi ballari',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='ScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('compliance', 'Compliance'), ('financial', 'Moliyaviy'), ('technical', 'Texnik'), ('experience', 'Tajriba'), ('price', 'Narx'), ('delivery', 'Yetkazib berish'), ('warranty', 'Kafolat')], max_length=20, verbose_name='Ball turi')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maksimal ball')),
                ('achieved_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Erishilgan ball')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Foiz')),
                ('analysis', models.TextField(verbose_name='Tahlil')),
                ('reasoning', models.TextField(verbose_name='Sabablari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ball tafsilotlari',
                'verbose_name_plural': 'Ball tafsilotlari',
            },
        ),
        migrations.CreateModel(
            name='TenderAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=500, verbose_name='Tender nomi')),
                ('tender_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tender turi')),
                ('tender_data', models.JSONField(default=dict, verbose_name='Tender tahlili')),
                ('participants', models.JSONField(default=list, verbose_name='Ishtirokchilar tahlili')),
                ('participant_count', models.IntegerField(default=0, verbose_name='Ishtirokchilar soni')),
                ('ranking', models.JSONField(default=list, verbose_name='Reyting')),
                ('winner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="G'olib")),
                ('winner_score', models.FloatField(blank=True, null=True, verbose_name="G'olib balli")),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Xulosa')),
                ('language', models.CharField(default='uz', max_length=10, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Tender tahlil natijasi',
                'verbose_name_plural': 'Tender tahlil natijalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
