# Generated by Django 5.0.1 on 2026-01-12 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('participants', '0002_initial'),
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Baholovchi'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='evaluationlog',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='participantscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_scores', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='participantscore',
            name='tender_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='participants.tenderparticipant'),
        ),
        migrations.AddField(
            model_name='scoredetail',
            name='participant_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_details', to='evaluations.participantscore'),
        ),
        migrations.AlterUniqueTogether(
            name='participantscore',
            unique_together={('evaluation', 'tender_participant')},
        ),
        migrations.AlterUniqueTogether(
            name='scoredetail',
            unique_together={('participant_score', 'score_type')},
        ),
    ]
