# Generated by Django 5.0.1 on 2026-01-07 09:36

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tender nomi')),
                ('description', models.TextField(verbose_name='Tender tavsifi')),
                ('tender_number', models.CharField(max_length=100, unique=True, verbose_name='Tender raqami')),
                ('organization', models.CharField(max_length=300, verbose_name='Tashkilot')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('evaluation', 'Baholash'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holati')),
                ('tender_type', models.CharField(choices=[('open', 'Ochiq tender'), ('closed', 'Yopiq tender'), ('two_stage', 'Ikki bosqichli tender')], default='open', max_length=20, verbose_name='Tender turi')),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Taxminiy byudjet')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Valyuta')),
                ('start_date', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_date', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirements_document', models.FileField(blank=True, null=True, upload_to='tenders/requirements/', verbose_name='Talablar hujjati')),
                ('technical_specification', models.FileField(blank=True, null=True, upload_to='tenders/technical/', verbose_name='Texnik spetsifikatsiya')),
                ('requirements_vector', pgvector.django.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Talablar vektori')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenderlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Hujjat nomi')),
                ('document_type', models.CharField(choices=[('requirements', 'Talablar hujjati'), ('technical', 'Texnik spetsifikatsiya'), ('financial', 'Moliyaviy hujjat'), ('other', 'Boshqa hujjat')], max_length=20, verbose_name='Hujjat turi')),
                ('file', models.FileField(upload_to='tenders/documents/', verbose_name='Hujjat fayli')),
                ('file_size', models.BigIntegerField(verbose_name='Fayl hajmi (bayt)')),
                ('file_type', models.CharField(max_length=50, verbose_name='Fayl turi')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Sahifalar soni')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Ajratilgan matn')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Ishlov berildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Tender hujjati',
                'verbose_name_plural': 'Tender hujjatlari',
            },
        ),
        migrations.CreateModel(
            name='TenderRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Talab nomi')),
                ('description', models.TextField(verbose_name='Talab tavsifi')),
                ('requirement_type', models.CharField(choices=[('technical', 'Texnik talab'), ('financial', 'Moliyaviy talab'), ('legal', 'Huquqiy talab'), ('experience', 'Tajriba talabi'), ('certification', 'Sertifikat talabi')], max_length=20, verbose_name='Talab turi')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Vazni')),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Maksimal ball')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Majburiy')),
                ('requirement_vector', pgvector.django.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Talab vektori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Tender talabi',
                'verbose_name_plural': 'Tender talablari',
            },
        ),
    ]
