# Generated by Django 5.0.1 on 2026-01-07 09:36

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='Kompaniya nomi')),
                ('company_type', models.CharField(choices=[('llc', 'MChJ'), ('jsc', 'AJ'), ('ie', "Yuridik shaxs bo'lmagan tadbirkor"), ('state', 'Davlat korxonasi'), ('foreign', 'Xorijiy kompaniya')], max_length=20, verbose_name='Kompaniya turi')),
                ('tax_identification_number', models.CharField(max_length=20, unique=True, verbose_name='INN/STIR')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name="Ro'yxatdan o'tish raqami")),
                ('legal_address', models.TextField(verbose_name='Yuridik manzil')),
                ('actual_address', models.TextField(verbose_name='Haqiqiy manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('director_name', models.CharField(max_length=200, verbose_name='Direktor F.I.O.')),
                ('director_phone', models.CharField(max_length=20, verbose_name='Direktor telefoni')),
                ('director_email', models.EmailField(max_length=254, verbose_name='Direktor emaili')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('blacklisted', "Qora ro'yxatda")], default='active', max_length=20, verbose_name='Holati')),
                ('trust_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Ishonch reytingi')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='participants/certificates/', verbose_name="Ro'yxatdan o'tish guvohnomasi")),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='participants/tax/', verbose_name="Soliq to'lov sertifikati")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ishtirokchi',
                'verbose_name_plural': 'Ishtirokchilar',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='TenderParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tish vaqti")),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='Ariza topshirish vaqti')),
                ('status', models.CharField(choices=[('registered', "Ro'yxatdan o'tgan"), ('submitted', 'Ariza topshirgan'), ('qualified', 'Saralangan'), ('disqualified', "Saralashdan o'tmagan"), ('winner', "G'olib"), ('withdrawn', 'Chekinagan')], default='registered', max_length=20, verbose_name='Holati')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Taklif etilgan narx')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Valyuta')),
                ('delivery_time', models.IntegerField(blank=True, null=True, verbose_name='Yetkazib berish muddati (kun)')),
                ('warranty_period', models.IntegerField(blank=True, null=True, verbose_name='Kafolat muddati (oy)')),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='Taklif hujjati')),
                ('financial_document', models.FileField(blank=True, null=True, upload_to='proposals/financial/', verbose_name='Moliyaviy hujjat')),
                ('technical_document', models.FileField(blank=True, null=True, upload_to='proposals/technical/', verbose_name='Texnik hujjat')),
                ('proposal_vector', pgvector.django.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Taklif vektori')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_participations', to='participants.participant')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'Tender ishtirokchisi',
                'verbose_name_plural': 'Tender ishtirokchilari',
                'ordering': ['-registration_date'],
                'unique_together': {('tender', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Hujjat nomi')),
                ('document_type', models.CharField(choices=[('proposal', 'Taklif hujjati'), ('financial', 'Moliyaviy hujjat'), ('technical', 'Texnik hujjat'), ('certificate', 'Sertifikat'), ('experience', 'Tajriba hujjati'), ('other', 'Boshqa hujjat')], max_length=20, verbose_name='Hujjat turi')),
                ('file', models.FileField(upload_to='participants/documents/', verbose_name='Hujjat fayli')),
                ('file_size', models.BigIntegerField(verbose_name='Fayl hajmi (bayt)')),
                ('file_type', models.CharField(max_length=50, verbose_name='Fayl turi')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Sahifalar soni')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Ajratilgan matn')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Ishlov berildi')),
                ('created_by_software', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yaratilgan dastur')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi o'zgartirish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='participants.tenderparticipant')),
            ],
            options={
                'verbose_name': 'Ishtirokchi hujjati',
                'verbose_name_plural': 'Ishtirokchi hujjatlari',
            },
        ),
    ]
