# Generated by Django 5.0.1 on 2026-01-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderparticipant',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tenders.tender'),
        ),
        migrations.AddField(
            model_name='participantdocument',
            name='tender_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='participants.tenderparticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='tenderparticipant',
            unique_together={('tender', 'participant')},
        ),
    ]
